In [1]:
# imports
import pandas as pd
from pandas_profiling import ProfileReport
import orga_functions as org

In [2]:
# read in the dataframes
df = pd.read_csv(org.path("01_AirQuality_processed.csv"), sep=';')
feature_df = pd.read_csv(org.path("00_FeatureList_original.csv"), sep =";")

In [3]:
profile = ProfileReport(df, title = "AirQuality Report")

In [4]:
df

,date,co_gt,pt08_s1_co,nmhc_gt,c6h6_gt,pt08_s2_nmhc,nox_gt,pt08_s3_nox,no2_gt,pt08_s4_no2,pt08_s5_o3,t,rh,ah
0,2004-03-10 18:00:00,2.6,1360.0,150.0,11.9,1046.0,166.0,1056.0,113.0,1692.0,1268.0,13.6,48.9,0.7578
1,2004-03-10 19:00:00,2.0,1292.0,112.0,9.4,955.0,103.0,1174.0,92.0,1559.0,972.0,13.3,47.7,0.7255
2,2004-03-10 20:00:00,2.2,1402.0,88.0,9.0,939.0,131.0,1140.0,114.0,1555.0,1074.0,11.9,54.0,0.7502
3,2004-03-10 21:00:00,2.2,1376.0,80.0,9.2,948.0,172.0,1092.0,122.0,1584.0,1203.0,11.0,60.0,0.7867
4,2004-03-10 22:00:00,1.6,1272.0,51.0,6.5,836.0,131.0,1205.0,116.0,1490.0,1110.0,11.2,59.6,0.7888
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7993,2005-02-06 19:00:00,1.6,985.0,NaN,4.5,736.0,227.0,891.0,165.0,875.0,774.0,6.0,38.0,0.3584
7994,2005-02-06 20:00:00,1.8,1002.0,NaN,5.3,780.0,252.0,855.0,179.0,892.0,857.0,5.8,36.4,0.3385
7995,2005-02-06 21:00:00,1.4,938.0,NaN,3.7,692.0,193.0,937.0,149.0,805.0,737.0,5.8,35.4,0.3286
7996,2005-02-06 22:00:00,1.1,896.0,NaN,2.6,627.0,158.0,1033.0,126.0,782.0,610.0,5.4,36.6,0.3304
7997,2005-02-06 23:00:00,1.0,907.0,NaN,2.4,614.0,150.0,1052.0,120.0,782.0,627.0,5.1,37.9,0.3358

In [5]:
feature_df

,names,mean,min,25%,50%,75%,max,erlÃ¤uterung
0,co_gt,2.168604,0.1000,1.1000,1.8000,2.9000,11.900,stuendlich gemittelte CO-Konzentration
1,pt08_s1_co,1098.303412,647.0000,932.0000,1061.0000,1234.0000,2040.000,stuendlich gemittelte Sensorreaktion (nominell...
2,nmhc_gt,218.607666,7.0000,66.0000,145.0000,297.0000,1189.000,stuendlich gemittelte Gesamtkonzentration an n...
3,c6h6_gt,10.458205,0.1000,4.7000,8.6000,14.4000,63.700,stuendlich gemittelte Benzolkonzentration
4,pt08_s2_nmhc,953.579453,383.0000,749.0000,925.0000,1130.0000,2214.000,stuendlich gemittelte Sensorreaktion (nominell...
5,nox_gt,232.360072,2.0000,89.0000,164.0000,303.7500,1479.000,Echte stuendlich gemittelte NOx-Konzentration
6,pt08_s3_nox,848.762615,322.0000,672.0000,818.0000,984.0000,2683.000,stuendlich gemitteltes Sensoransprechverhalten...
7,no2_gt,106.251831,2.0000,73.0000,103.0000,132.0000,333.000,stuendlich gemittelte NO2-Konzentration
8,pt08_s4_no2,1507.352834,657.0000,1305.0000,1508.0000,1707.0000,2775.000,stuendlich gemittelte Sensorreaktion (nominell...
9,pt08_s5_o3,1024.200026,253.0000,737.0000,962.0000,1272.0000,2523.000,stuendlich gemitteltes Sensoransprechverhalten...
10,t,19.476041,0.3000,13.1000,19.3000,25.4000,44.600,Temperatur
11,rh,48.969244,9.2000,35.5000,49.4000,62.1000,88.700,Relative Luftfeuchtigkeit
12,ah,1.082099,0.1988,0.8167,1.0468,1.3713,2.231,Absolute Luftfeuchtigkeit
13,month,6.928525,1.0000,4.0000,7.0000,10.0000,12.000,Monate der Erfassung
14,hour,11.488520,0.0000,6.0000,11.0000,17.0000,23.000,Stunden der Erfassung

In [6]:
# name with discription
name = feature_df["names"].values
discription= feature_df["erlÃ¤uterung"].values
name_dict = dict(zip(name, discription))

In [7]:
profile.config.variables.descriptions = name_dict

In [8]:
# save the report as HTML
file_path = org.path("AirQuality_report.html")
profile.to_file(output_file = file_path)

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]