# Purpose of the Notebook:

In this Notebook a new CSV file for continouos updates is created.

# Create a CSV file for continouos updates

In [1]:
# imports
import pandas as pd
import orga_functions as org
import X4_ReadJSON as readj

In [2]:
df = pd.read_csv(org.path("02_AirQuality_processed.csv"), sep=';', index_col='date')

In [3]:
df

,co_gt,pt08_s1_co,nmhc_gt,c6h6_gt,pt08_s2_nmhc,nox_gt,pt08_s3_nox,no2_gt,pt08_s4_no2,pt08_s5_o3,t,rh,ah
date,,,,,,,,,,,,,
2004-03-10 18:00:00,2.6,1360.0,150.000000,11.9,1046.000000,166.0,1056.0,113.0,1692.0,1268.0,13.6,48.9,0.7578
2004-03-10 19:00:00,2.0,1292.0,112.000000,9.4,955.000000,103.0,1174.0,92.0,1559.0,972.0,13.3,47.7,0.7255
2004-03-10 20:00:00,2.2,1402.0,88.000000,9.0,939.000000,131.0,1140.0,114.0,1555.0,1074.0,11.9,54.0,0.7502
2004-03-10 21:00:00,2.2,1376.0,80.000000,9.2,948.000000,172.0,1092.0,122.0,1584.0,1203.0,11.0,60.0,0.7867
2004-03-10 22:00:00,1.6,1272.0,51.000000,6.5,836.000000,131.0,1205.0,116.0,1490.0,1110.0,11.2,59.6,0.7888
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2005-02-06 19:00:00,1.6,985.0,218.607666,4.5,953.579453,227.0,891.0,165.0,875.0,774.0,6.0,38.0,0.3584
2005-02-06 20:00:00,1.8,1002.0,218.607666,5.3,780.000000,252.0,855.0,179.0,892.0,857.0,5.8,36.4,0.3385
2005-02-06 21:00:00,1.4,938.0,218.607666,3.7,953.579453,193.0,937.0,149.0,805.0,737.0,5.8,35.4,0.3286
2005-02-06 22:00:00,1.1,896.0,218.607666,2.6,953.579453,158.0,1033.0,126.0,782.0,610.0,5.4,36.6,0.3304
2005-02-06 23:00:00,1.0,907.0,218.607666,2.4,953.579453,150.0,1052.0,120.0,782.0,627.0,5.1,37.9,0.3358

In [4]:
# save 
new_path = org.path("03_AirQuality_continuous.csv")
df.to_csv(new_path, sep=';', index = True)